services:
  #  БАЗА ДАННЫХ
  postgres:
    image: postgres:15-alpine
    container_name: modhub_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  #  ГЛАВНЫЙ API
  core-api:
    build: ./services/core-api
    container_name: modhub_core_api
    restart: always
    environment:
      - PORT=${CORE_API_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy

  #  БРОКЕР СООБЩЕНИЙ KAFKA
  kafka:
    image: apache/kafka:3.7.0
    container_name: modhub_kafka
    restart: always
    environment:
      KAFKA_NODE_ID: ${KAFKA_NODE_ID}
      KAFKA_PROCESS_ROLES: ${KAFKA_PROCESS_ROLES}
      KAFKA_LISTENERS: ${KAFKA_LISTENERS}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_CONTROLLER_LISTENER_NAMES: ${KAFKA_CONTROLLER_LISTENER_NAMES}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CONTROLLER_QUORUM_VOTERS}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: ${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR}

  #  S3 СОВМЕСТИМОЕ ХРАНИЛИЩЕ MINIO
  minio:
    image: minio/minio:latest
    container_name: modhub_minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  #  ВСПОМОГАЮЩИЙ КОНТЕЙНЕР MINIO
  minio-init:
    image: minio/mc:latest
    container_name: modhub_minio_init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      mc mb myminio/${MINIO_BUCKET} || true; 
      mc anonymous set download myminio/${MINIO_BUCKET};
      exit 0;
      "

  # АНТИВИРУС CLAMAV
  clamav:
    image: clamav/clamav:latest
    container_name: modhub_clamav
    restart: always

  # СЕРВИС ДЛЯ РАБОТЫ CLAMAV
  scanner-worker:
    build:
      context: ./services/scanner-worker
    container_name: modhub_scanner_worker
    restart: always
    depends_on:
      - kafka
      - postgres
      - clamav
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - DB_PORT=${DB_PORT}

  frontend:
    build:
      context: ./client
    container_name: modhub_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - core-api

volumes:
  pg_data:
  minio_data: